"use client";

import { FormEvent } from "react";

export default function ContactForm() {
  function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); }
  const input = "mt-2 w-full rounded-md border border-[#092C42]/15 bg-white px-4 py-3 text-sm text-[#092C42] outline-none transition-colors placeholder:text-[#092C42]/40 focus:border-[#FC4C00] focus:ring-1 focus:ring-[#FC4C00]";
  return <form onSubmit={handleSubmit} className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-[#092C42]">Name<input required name="name" className={input} placeholder="Your name" /></label><label className="text-sm font-medium text-[#092C42]">Company<input name="company" className={input} placeholder="Company name" /></label></div><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-[#092C42]">Email<input required type="email" name="email" className={input} placeholder="you@company.com" /></label><label className="text-sm font-medium text-[#092C42]">Phone<input name="phone" className={input} placeholder="Phone number" /></label></div><label className="block text-sm font-medium text-[#092C42]">Service<select name="service" className={input} defaultValue=""><option value="" disabled>Select a capability</option><option>Creative</option><option>Web</option><option>Software</option><option>Cloud</option><option>Growth</option><option>Other</option></select></label><label className="block text-sm font-medium text-[#092C42]">Project description<textarea required name="description" rows={5} className={input} placeholder="Tell us what you are trying to build, improve or grow." /></label><label className="block text-sm font-medium text-[#092C42]">Budget range <span className="font-normal text-[#092C42]/50">(optional)</span><input name="budget" className={input} placeholder="e.g. Request a quote" /></label><button type="submit" className="group inline-flex items-center justify-center gap-2 rounded-md bg-[#FC4C00] px-6 py-3 text-sm font-semibold tracking-wide text-white transition-all hover:bg-[#e34400] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FC4C00] focus-visible:ring-offset-2">SEND ENQUIRY<span aria-hidden="true" className="transition-transform group-hover:translate-x-1">→</span></button></form>;
}
